baseURL                   = "https://oskoss.github.io"
builddrafts                = false
languageCode               = "en"
canonifyurls               = true
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "public"
enableEmoji                = true
hasCJKLanguage             = false
summaryLength              = 200
Paginate                   = 3

theme                      = "AllinOne"
title                      = "Peter Blum"

pygmentsuseclasses         = true

[permalinks]
  blog                     = "blog/:year-:month/:slug/"

[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"

[menu]
  [[menu.main]]
    name                   = "Blog"
    weight                 = -120
    identifier             = "blog"
    url                    = "posts/"  

  [[menu.main]]
    name                   = "Resume"
    weight                 = -110
    identifier             = "resume"
    url                    = "resume/" 

  [[menu.main]]
    name                   = "Contact"
    weight                 = -100
    identifier             = "contact"
    url                    = "contact/"  

[params]
  faviconfile              = "img/favicon.ico"               # from static/
  avatar                   = "img/profile.png"             # path to image in static dir e.g img/avatar.png 
  author                   = "Peter Blum"
  description              = ["Be better.", "Do what you can't.", "Love the world."]           # appears in the site header when set to a non-empty string
  welcome_head             = ""
  welcome_word             = ""

  latestpostscount         = 3                             # how many posts to display on the home page
  bloggroupby              = 'month'
  dateform                 = "Jan 2, 2006"
  dateformfull             = "2006-01-02  Monday  15:04:05"
  noshowreadtime           = false                         # if true, don't show "<x> minutes read" in posts

  # slides
  slidesDirPath            = "static/img/front-page"    # path to image in local dir (path for hugo)
  slidesDirPathURL         = "img/front-page"    # path to image in static dir (for static pages)

  # highlighting 
  highlightjs              = true

  # latex
  katex                    = true

  # links
  email                    = "peterblum@outlook.com"
  github                   = "//github.com/oskoss"
  linkedin                 = "//linkedin.com/in/pblum/"
  twitter                  = "//twitter.com/_PBlum" 
  include_rss              = false                          # include RSS <link> tag in <head> and show RSS icon

  # analytics
  googleAnalytics          = "your-google-analytic-id"
  logoText = "story.pb"